auto: true
pygments: true

title: Rozifus Dev

url: http://www.rozifus.com

permalink: /:categories/:title

author:
    name: Ryan Miller
    email: rozifus@gmail.com
    github: rozifus
    twitter: Rozifus

