auto: true
pygments: true

title: Rozifus Dev

url: http://localhost:4000

permalink: /:categories/:title

author:
    name: Ryan Miller
    email: rozifus@gmail.com
    github: rozifus
    twitter: RyanMillerApps

