auto: true
pygments: true

title: Rozifus Dev
description: Ryan Miller's Software Development

url: http://www.rozifus.com
canonical-url: http://rozifus.com

permalink: /:categories/:title

author:
    name: Ryan Miller
    email: rozifus@gmail.com
    github: rozifus
    twitter: rozifus
    gravatar: http://www.gravatar.com/avatar/7ee73ed44153d21b1167f560545e094d.png

